[package]
name = "YaScript2"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.12", features = [ "derive" ] }
pollster = "0.3.0"
wgpu = { version = "22.1.0", default-features = false, features = ["dx12", "wgsl"] }
winit = { version = "0.29.*", features = ["rwh_05"] }
